#:kivy 2.1.0

#:import NoTransition kivy.uix.screenmanager.NoTransition
#:include screen_splash.kv
#:include screen_main.kv

ScreenManager:
    id: screen_manager
    transition: NoTransition()
    Screen:
        name: 'screen_splash'
        ScreenSplash:
            app_window: app
            screen_manager: screen_manager

    Screen:
        name: 'screen_main'
        ScreenMain:
            id: screen_main
            screen_manager: screen_manager
